python3 -m sglang.launch_server   --model /raid/models/DeepSeek-R1-0528/  \
        --trust-remote-code     --host 0.0.0.0 --port 30000     \
        --tp 8 --ep 8       \
        --attention-backend flashinfer \
        --max-running-requests 128 --cuda-graph-max-bs 128     \
        --stream-output     \
        --mem-fraction-static 0.80     \
        --disable-radix-cache     \
        --max-prefill-tokens 8192 \
        --chunked-prefill-size 8192 \
        --enable-dp-attention 
